[versions]

kotlin = "2.1.20"
compose = "1.9.0-rc01"
composeIcons = "1.1.1"
materialKolor = "2.0.1"
kotlinx-coroutines = "1.10.1"
hotreload = "1.0.0-beta06"
landscapist = "2.5.0"
preloader = "1.0.3"

[libraries]

composeIcons-fontAwesome = { module = "br.com.devsrsouza.compose.icons:font-awesome", version.ref = "composeIcons" }
materialKolor = { module = "com.materialkolor:material-kolor", version.ref = "materialKolor" }
kotlinx-coroutines-swing = { group = "org.jetbrains.kotlinx", name = "kotlinx-coroutines-swing", version.ref = "kotlinx-coroutines" }
landscapist-coil = { module = "com.github.skydoves:landscapist-coil3", version.ref = "landscapist" }
landscapist-placeholder = { module = "com.github.skydoves:landscapist-placeholder", version.ref = "landscapist" }

[plugins]

multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
compose = { id = "org.jetbrains.compose", version.ref = "compose" }
hotreload = { id = "org.jetbrains.compose.hot-reload", version.ref = "hotreload" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
preloader = { id = "com.ryinex.kotlin.browser.preloader", version.ref = "preloader" }